### ISSUE TITLE
Verify repo state

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/k8-java-api-code-samples#9]
Please verify that the repo and OVA , AMI produced out of are in good shape, i.e. available, updated, usable and stable.

Please create a live server on EC2 and another one on one of the ESXi servers.

**Comment by NourEddineX** [comment]
Fixed a small issue in #12 

Setup script for OVA/AMI for packer [here](https://github.com/k8-proxy/vmware-scripts/pull/91)
